export const generateCreateOrderBody = (shipment: any) => {
  return {
    order_id: shipment.orderNumber,
    order_date: shipment.orderDate,
    pickup_location: shipment.warehouse.name,
    // channel_id: "",
    // comment: "",
    billing_customer_name: shipment.delivery.name,
    billing_last_name: "",
    billing_address: shipment.delivery.address,
    // billing_address_2: "",
    billing_city: shipment.delivery.city,
    billing_pincode: shipment.delivery.pincode,
    billing_state: shipment.delivery.state,
    billing_country: shipment.delivery.country,
    billing_email: shipment.delivery.email,
    billing_phone: shipment.delivery.phone,
    shipping_is_billing: true,
    // shipping_customer_name: "",
    // shipping_last_name: "",
    // shipping_address: "",
    // shipping_address_2: "",
    // shipping_city: "",
    // shipping_pincode: "",
    // shipping_country: "",
    // shipping_state: "",
    // shipping_email: "",
    // shipping_phone: "",
    order_items: shipment.items.map((item: any) => ({
      name: item.name,
      sku: item.sku,
      units: item.quantity,
      selling_price: item.price,
      // discount: item.discount,
      // tax: item.tax,
      // hsn: item.hsn,
    })),
    payment_method: shipment.payment.mode,
    shipping_charges: shipment.payment.delivery,
    giftwrap_charges: shipment.payment.giftwrap,
    transaction_charges: 0,
    total_discount: 0,
    sub_total: shipment.payment.totalAmount,
    length: shipment.box.length,
    breadth: shipment.box.width,
    height: shipment.box.height,
    weight: Number(shipment.box.weight) / 1000,
  };
};
